CREATE TABLE IF NOT EXISTS dim_ibge_demografico (
    dem_id INT AUTO_INCREMENT PRIMARY KEY,
    dem_ibge_codigo VARCHAR(7) NOT NULL,
    dem_ano YEAR NOT NULL,
    dem_pop_total BIGINT NULL,
    dem_pop_urbana BIGINT NULL,
    dem_pop_rural BIGINT NULL,
    dem_pop_homens BIGINT NULL,
    dem_pop_mulheres BIGINT NULL,
    dem_densidade_demografica DECIMAL(12,4) NULL,
    dem_pop_0_14 BIGINT NULL,
    dem_pop_15_64 BIGINT NULL,
    dem_pop_65_mais BIGINT NULL,
    dem_taxa_crescimento DECIMAL(6,4) NULL,
    dem_fonte VARCHAR(255) NULL,
    dem_criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    dem_atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ibge_ano (dem_ibge_codigo, dem_ano),
    INDEX idx_ibge (dem_ibge_codigo),
    INDEX idx_ano (dem_ano)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dim_ibge_pib_municipal (
    pib_id INT AUTO_INCREMENT PRIMARY KEY,
    pib_ibge_codigo VARCHAR(7) NOT NULL,
    pib_ano YEAR NOT NULL,
    pib_total DECIMAL(18,2) NULL,
    pib_per_capita DECIMAL(18,2) NULL,
    pib_agropecuaria DECIMAL(18,2) NULL,
    pib_industria DECIMAL(18,2) NULL,
    pib_servicos DECIMAL(18,2) NULL,
    pib_administracao_publica DECIMAL(18,2) NULL,
    pib_impostos DECIMAL(18,2) NULL,
    pib_va_total DECIMAL(18,2) NULL,
    pib_fonte VARCHAR(255) NULL,
    pib_criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    pib_atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_pib_ibge_ano (pib_ibge_codigo, pib_ano),
    INDEX idx_pib_ibge (pib_ibge_codigo),
    INDEX idx_pib_ano (pib_ano)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dim_ibge_indices_socioeconomicos (
    idx_id INT AUTO_INCREMENT PRIMARY KEY,
    idx_ibge_codigo VARCHAR(7) NOT NULL,
    idx_ano YEAR NOT NULL,
    idx_idhm DECIMAL(6,4) NULL,
    idx_idhm_renda DECIMAL(6,4) NULL,
    idx_idhm_longevidade DECIMAL(6,4) NULL,
    idx_idhm_educacao DECIMAL(6,4) NULL,
    idx_renda_per_capita DECIMAL(18,2) NULL,
    idx_gini DECIMAL(6,4) NULL,
    idx_percentual_pobres DECIMAL(6,3) NULL,
    idx_percentual_extrema_pobreza DECIMAL(6,3) NULL,
    idx_taxa_alfabetizacao DECIMAL(6,3) NULL,
    idx_anos_estudo_medio DECIMAL(6,3) NULL,
    idx_frequencia_escolar_6_14 DECIMAL(6,3) NULL,
    idx_taxa_desemprego DECIMAL(6,3) NULL,
    idx_taxa_formalizacao DECIMAL(6,3) NULL,
    idx_esperanca_vida DECIMAL(6,3) NULL,
    idx_mortalidade_infantil DECIMAL(6,3) NULL,
    idx_fonte VARCHAR(255) NULL,
    idx_criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    idx_atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_idx_ibge_ano (idx_ibge_codigo, idx_ano),
    INDEX idx_idx_ibge (idx_ibge_codigo),
    INDEX idx_idx_ano (idx_ano)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dim_ibge_infraestrutura (
    inf_id INT AUTO_INCREMENT PRIMARY KEY,
    inf_ibge_codigo VARCHAR(7) NOT NULL,
    inf_ano YEAR NOT NULL,
    inf_abastecimento_agua DECIMAL(6,3) NULL,
    inf_esgotamento_sanitario DECIMAL(6,3) NULL,
    inf_coleta_lixo DECIMAL(6,3) NULL,
    inf_energia_eletrica DECIMAL(6,3) NULL,
    inf_leitos_hospitalares INT NULL,
    inf_leitos_por_1000_hab DECIMAL(6,3) NULL,
    inf_estabelecimentos_saude INT NULL,
    inf_medicos_por_1000_hab DECIMAL(6,3) NULL,
    inf_escolas_fundamental INT NULL,
    inf_escolas_medio INT NULL,
    inf_escolas_superior INT NULL,
    inf_agencias_bancarias INT NULL,
    inf_correios INT NULL,
    inf_fonte VARCHAR(255) NULL,
    inf_criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    inf_atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_inf_ibge_ano (inf_ibge_codigo, inf_ano),
    INDEX idx_inf_ibge (inf_ibge_codigo),
    INDEX idx_inf_ano (inf_ano)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
